export const GROCERY_INSTANCES_LOADING = "GROCERY_INSTANCES_LOADING";
export const GROCERY_INSTANCES_FAILED = "GROCERY_INSTANCES_FAILED";
export const ADD_GROCERY_INSTANCES = "ADD_GROCERY_INSTANCES";
export const CROSS_OUT_GROCERY_INSTANCE = "CROSS_OUT_GROCERY_INSTANCE";

export const GROCERY_CATEGORIES_LOADING = "GROCERY_CATEGORIES_LOADING";
export const GROCERY_CATEGORIES_FAILED = "GROCERY_CATEGORIES_FAILED";
export const ADD_GROCERY_CATEGORIES = "ADD_GROCERY_CATEGORIES";
export const CLICK_CATEGORY = "CLICK_CATEGORY";
export const CATEGORY_SECTION_CHANGE = "CATEGORY_SECTION_CHANGE";

export const RECIPES_LOADING = "RECIPES_LOADING";
export const RECIPES_FAILED = "RECIPES_FAILED";
export const ADD_RECIPES = "ADD_RECIPES";

export const SET_RECIPE_CATEGORY = "SET_RECIPE_CATEGORY";

export const SET_RECIPES_CATEGORIES_FETCHED = "SET_RECIPES_CATEGORIES_FETCHED";

export const FILTER_RECIPES = "FILTER_RECIPES";

export const ADD_NEW_GROCERY = "ADD_NEW_GROCERY";
export const MODIFY_NEW_GROCERY = "MODIFY_NEW_GROCERY";

export const GROCERIES_LOADING = "GROCERIES_LOADING";
export const GROCERIES_FAILED = "GROCERIES_FAILED";
export const ADD_GROCERIES = "ADD_GROCERIES";

export const FILTER_GROCERIES = "FILTER_GROCERIES";

export const SET_SEARCH_ACTIVE = "SET_SEARCH_ACTIVE";

export const CHANGE_GROCERY_SEARCH_VALUE = "CHANGE_GROCERY_SEARCH_VALUE";

export const CREATE_REF = "CREATE_REF";

export const SET_HISTORY = "SET_HISTORY";
